-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 12:11:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema acme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema acme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `acme` DEFAULT CHARACTER SET utf8 ;
USE `acme` ;

-- -----------------------------------------------------
-- Table `acme`.`TBL_Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acme`.`TBL_Persona` (
  `id` INT NOT NULL,
  `PSN_Numero_Cedula_Persona` VARCHAR(15) NOT NULL,
  `PSN_Primer_Nombre_Persona` VARCHAR(25) NOT NULL,
  `PSN_Segundo_Nombre_Persona` VARCHAR(25) NULL,
  `PSN_Apellidos_Persona` VARCHAR(50) NOT NULL,
  `PSN_Direccion_Residencia_Persona` VARCHAR(100) NOT NULL,
  `PSN_Telefono_Persona` VARCHAR(15) NOT NULL,
  `PSN_Ciudad_Residencia_Persona` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `PSN_Numero_Cedula_Persona_UNIQUE` (`PSN_Numero_Cedula_Persona` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acme`.`TBL_Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `acme`.`TBL_Vehiculo` (
  `id` INT NOT NULL,
  `VHC_Placa_Vehiculo` VARCHAR(10) NOT NULL,
  `VHC_Color_Vehiculo` VARCHAR(10) NOT NULL,
  `VHC_Marca_Vehiculo` VARCHAR(25) NOT NULL,
  `VHC_Tipo_Vehiculo` VARCHAR(10) NOT NULL,
  `VHC_Propietario_Id` INT NOT NULL,
  `VHC_Conductor_Id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `VHC_Placa_Vehiculo_UNIQUE` (`VHC_Placa_Vehiculo` ASC) VISIBLE,
  INDEX `fk_TBL_Vehiculo_TBL_Persona_idx` (`VHC_Propietario_Id` ASC) VISIBLE,
  INDEX `fk_TBL_Vehiculo_TBL_Persona1_idx` (`VHC_Conductor_Id` ASC) VISIBLE,
  CONSTRAINT `fk_TBL_Vehiculo_TBL_Persona`
    FOREIGN KEY (`VHC_Propietario_Id`)
    REFERENCES `acme`.`TBL_Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TBL_Vehiculo_TBL_Persona1`
    FOREIGN KEY (`VHC_Conductor_Id`)
    REFERENCES `acme`.`TBL_Persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
